### ISSUE TITLE
Create shared .dll with all sign in/out methods

### ISSUE THREAD

**Issue by miyconst** [StarcounterSamples/Polyjuice#30]
There are three applications which copy paste same code:
- `SignIn`
- `GoogleSignIn`
- `UserAdminApp`

And we are planning to add `JsonTookenSignIn`.

There should be a shared .dll with all those classes and methods. Maybe a class `Auth` (or any other name) should be build in Polyjuice so every application could check whether user signed in and which user.

**Comment by warpech** [comment]
Shared DLL is not a way to go. Using commit hooks is a way to go. Can this be closed?

**Comment by miyconst** [comment]
We can close this issue, not because of commit hooks, but because we refuse to let apps know about each other. Though I don't see how would SignIn app know about GoogleSignIn if they both would use a `.dll`.

I don't want to copy paste same code among apps, and commit hooks don't solve this issue.

**Comment by dan31** [comment]
Guys, let's get back to basics of the need – not to copy and paste the code. If I develop multiple applications as a single vendor, I would definitely do have shared code bits. How we can achieve that? I know I can *include the same source code file(s) into projects of each of the apps*. Then, once I have a mapper, it will be possible to include my shared mappers the same way. Today, as I recall, having multiple definitions of the same class won't become an issue even without mapper, since all apps are required to be namespaced internally, or they will simply use classes from Ontology. Any other options available rather than reusing single source code in multiple projects? And what do I miss in the reasoning?

**Comment by miyconst** [comment]
Why we cannot share a .dll between the apps? Even if I have some c# files to share, when copy-paste to an app, it should be namespaced inside that app. Next time I have to add some changes, I have to do that in multiply places. This is what I tried to avoid.

By the way, the code we are talking about does not have any db classes. I wanted to share the code for:

1. Check if session authenticated by sessionId.
2. Sign in user by login.
3. Sign in user by login and password.
4. Create new user.
5. Sign out.

Maybe some more, do not remember right now.

**Comment by warpech** [comment]
My (and I believe Dan's) thinking is: Starcounter eliminates the need for glue code. In case of *SignIn apps, we want to shrink the amount of code needed to log in a user, by first identifying what is that code and then how could we express it simpler.

As input, SignIn app uses username and password, GoogleSignIn uses external OAuth provider. 
As output, they both have their own database classes that are not shared, but mapped to a single ontology (this will be true in few weeks). Other apps subscribe to sessions using commit hooks.

I believe that whatever lies between the input and output as described above, should be shrinked to few lines of code. Perhaps the actions listed by @miyconst could be done as static methods of `Simplified.Ring5.SystemUserSession`?

**Comment by miyconst** [comment]
>Perhaps the actions listed by @miyconst could be done as static methods of `Simplified.Ring5.SystemUserSession`?

This is exactly what I was looking for. Those methods will be used not only by SignIn apps, but also all other apps which wanna check which user is signed in if signed in at all.

**Comment by dan31** [comment]
I try to summarize there a little bit, since we are onto important point of methodology. So, the way of sharing code (read – sharing logic) in Polyjuice way is to add this shared code to classes of your local model and/or your part/domain of outer rings in SO (upper model). For our case, Simplified is our local model that we build applications with, and we extend it with our needed shared logic. Correct?

**Comment by warpech** [comment]
Yes, this is the desired way. But then how do we send sign in/sign out information between shared classes? We need to provide an example using db mapping. @miyconst can you try to do that?

**Comment by miyconst** [comment]
>But then how do we send sign in/sign out information between shared classes?

@warpech we already have this with the commit hooks.

This is how I see it:

Each app which depends on sign in/out subscribes to commit hook for `SystemUserSession` class. 

The `SystemUserSession` class has a static method, something like `bool CheckSession(string SessionId)` or `List<SystemUserRole> GetSessionRoles(string SessionId)`. 

Inside the commit hook each app checks the session providing `Session.Current.SessionIdString` and does what is has to do.

**Comment by warpech** [comment]
I agree this is the way to go.

**Comment by miyconst** [comment]
Okay, then I assign it on me with low priority.

**Comment by miyconst** [comment]
The sign in methods are now moved to `Simplified.Ring3.SystemUser` class.
